
server:
  port: 8090


spring:
  profiles:
    active: local




---
spring:
  profiles: local
  datasource:
    name: ecommercedb
    url: jdbc:h2:mem:localdb
  jpa:
    show-sql: false
  #H2 settings
  h2:
    console:
      enabled: true
      path: /h2-console